#*********************************************************************
#
#  (C) 2001 J3d.org
#    http://code.j3d.org/
#
# Package makefile for the org.j3d.renderer.aviatrix3d.nodes directory
#
# Author: Alan Hudson
# Version: $Revision: 1.7 $
#
#*********************************************************************

PACKAGE = org.j3d.renderer.aviatrix3d.nodes

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  MaskedSwitch.java \
  BufferGeometry.java \
  IndexedBufferGeometry.java \
  TriangleArray.java \
  TriangleFanArray.java \
  TriangleStripArray.java \
  QuadArray.java \
  QuadStripArray.java \
  PointArray.java \
  LineArray.java \
  LineStripArray.java \
  IndexedTriangleArray.java \
  IndexedTriangleStripArray.java \
  IndexedTriangleFanArray.java \
  IndexedLineArray.java \
  IndexedLineStripArray.java \
  IndexedQuadArray.java \
  IndexedQuadStripArray.java \
  ObjectPlacer.java \
  SortedPointArray.java \
  Billboard.java \
  LODGroup.java \
  MarkerGroup.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =	j3d-org-util_1.1.0.jar j3d-org-geom-core_1.1.0.jar vecmath.jar

include ${PROJECT_ROOT}/make/Makefile.jav
