#*********************************************************************
#
#                                (C) 2004 j3d.org
#                             http://aviatrix3d.j3d.org/
#
# Package makefile for the standard directory
#
# Author: Justin Couch
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = standard

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = lighting.vert \
  fog.vert \
  fog.frag \
  texCoordGen.vert \
  texture.frag

include ${PROJECT_ROOT}/make/Makefile.shaders
