#*********************************************************************
#
#                      (C) 2003 Yumetech, Inc
#  		       http://aviatrix3d.j3d.org
#
#*********************************************************************

# Names of packages to be compiled. These are declared in the order that
# they are to be compiled in. We create one at a time
BUILD_ORDER = \
  standard \
  org.j3d.renderer.aviatrix3d.geom.hanim \

# A version number we tack onto the JAR file name for eclipse versioning
# purposes.
JAR_VERSION=2.2.0

# 3rd party libraries that need including.
JARS_3RDPARTY=

# Names of JAR files we want to create
JARS = aviatrix3d-glsl.jar

# Definitions of setup information if we are making a self-executable JAR
MAIN_CLASS     =
MAIN_PACKAGE   =
MAIN_JAR       = aviatrix3d-glsl.jar

include $(PROJECT_ROOT)/make/Makefile.shaders
