#*********************************************************************
#
#                                (C) 2004 J3d.org
#                             http://aviatrix3d.j3d.org/
#
# Package makefile for the org.j3d.renderer.aviatrix3d.geom.hanim directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.j3d.renderer.aviatrix3d.geom.hanim

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = mesh_skin.vert

include ${PROJECT_ROOT}/make/Makefile.shaders
