#*********************************************************************
#
#                         (C) 2001-06 j3d.org
#                         http://aviatrix3d.j3d.org/
#
# Package makefile producing aviatrix3d-all.jar
#
# Author: Justin Couch
# Version: $Revision: 1.20 $
#
#*********************************************************************

# No need to put in subdirs here. We only do that if we want to explicitly
# exclude some directory and then we name everything around it.
JAR_CONTENT= org/j3d/aviatrix3d	\
  org/j3d/aviatrix3d/picking \
  org/j3d/aviatrix3d/pipeline \
  org/j3d/aviatrix3d/pipeline/audio \
  org/j3d/aviatrix3d/pipeline/graphics \
  org/j3d/aviatrix3d/rendering \
  org/j3d/aviatrix3d/management \
  org/j3d/aviatrix3d/output/audio \
  org/j3d/aviatrix3d/output/graphics \
  org/j3d/aviatrix3d/iutil \
  org/j3d/renderer/aviatrix3d/device/input/keyboard \
  org/j3d/renderer/aviatrix3d/device/input/mouse \
  org/j3d/renderer/aviatrix3d/geom \
  org/j3d/renderer/aviatrix3d/geom/hanim \
  org/j3d/renderer/aviatrix3d/geom/particle \
  org/j3d/renderer/aviatrix3d/geom/volume \
  org/j3d/renderer/aviatrix3d/loader \
  org/j3d/renderer/aviatrix3d/loader/discreet \
  org/j3d/renderer/aviatrix3d/loader/dem \
  org/j3d/renderer/aviatrix3d/loader/stl \
  org/j3d/renderer/aviatrix3d/loader/vterrain \
  org/j3d/renderer/aviatrix3d/navigation \
  org/j3d/renderer/aviatrix3d/nodes \
  org/j3d/renderer/aviatrix3d/pipeline \
  org/j3d/renderer/aviatrix3d/texture \
  org/j3d/renderer/aviatrix3d/util \
  standard \
  config/i18n


# Manifest file name. Stored in the make/manifest directory
MANIFEST=all.mf

include ${PROJECT_ROOT}/make/Makefile.jav
