#*********************************************************************
#
#  (C) 2001-2006 J3d.org
#    http://code.j3d.org/
#
# Package makefile for the org.j3d.renderer.aviatrix3d.swt.draw2d directory
#
# Author: Justin Couch
# Version: $Revision: 1.4 $
#
#*********************************************************************

PACKAGE =  org.j3d.renderer.aviatrix3d.swt.draw2d


# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  FigureResizeHandler.java \
  BaseDraw2DSurface.java \
  SimpleDraw2DSurface.java \
  DebugDraw2DSurface.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-util_1.1.0.jar \
 org.j3d.opengl.swt.draw2d_0.7.0.jar \
 org.eclipse.draw2d_3.2.1.jar

include ${PROJECT_ROOT}/make/Makefile.jav
