/*****************************************************************************
 *                        Web3d.org Copyright (c) 2001
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 ****************************************************************************/

package org.j3d.aviatrix3d;

// External imports
// None

// Local imports
// None

/**
 * Traverses the render list and performs the specified operations.
 * <p>
 *
 * This list is generated by the Cull stage.
 *
 * @author Alan Hudson
 * @version $Revision: 1.2 $
 */
public interface DrawStage
{
    public static final int RENDER = 0;
    public static final int POSTRENDER = 1;

    /**
     * Draw all of the items to the surface now.
     *
     * @param renderList List of nodes to render
     * @param renderOp Operations to perform udring rhe render
     * @param size number of items in each list to work with
     */
    public void draw(Node[] renderList, int[] renderOp, int size);
}
