#*********************************************************************
#
#                         (C) 2003 - 2006 Yumetech, Inc
#                            http://www.j3d.org/
#
# Package makefile for the org.j3d.aviatrix3d directory
#
# Author: Justin Couch
# Version: $Revision: 2.28 $
#
#*********************************************************************

PACKAGE = org.j3d.aviatrix3d

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = AlreadyParentedException.java \
  InvalidNodeTypeException.java \
  InvalidDataTypeException.java \
  CyclicSceneGraphStructureException.java \
  InvalidWriteTimingException.java \
  InvalidListenerSetTimingException.java \
  InternalNodeUpdateListener.java \
  InternalLayerUpdateListener.java \
  MultipassRenderObserver.java \
  NodeUpdateListener.java \
  NodeUpdateHandler.java \
  TransformHierarchy.java \
  SceneGraphObject.java \
  ViewEnvironment.java \
  BaseSceneGraphObject.java \
  BoundingSphere.java \
  BoundingBox.java \
  BoundingVoid.java \
  BoundsUtils.java \
  PickingUtils.java \
  Node.java \
  MultiParentNode.java \
  BaseNode.java \
  BaseGroup.java \
  NodeComponent.java \
  BufferState.java \
  BoundingGeometry.java \
  Leaf.java \
  Layer.java \
  ViewportLayer.java \
  TextureSource.java \
  OffscreenTextureSource.java \
  PBufferTextureSource.java \
  MultipassTextureSource.java \
  MultipassTextureDestination.java \
  TextureComponent.java \
  TextureComponent1D.java \
  TextureComponent2D.java \
  TextureComponent3D.java \
  ImageTextureComponent2D.java \
  ImageTextureComponent3D.java \
  ByteTextureComponent1D.java \
  ByteTextureComponent2D.java \
  ByteTextureComponent3D.java \
  ByteBufferTextureComponent2D.java \
  ByteBufferTextureComponent3D.java \
  AudioSource.java \
  AudioComponent.java \
  ByteAudioComponent.java \
  Texture.java \
  TextureAttributes.java \
  TexCoordGeneration.java \
  TextureUnit.java \
  Viewpoint.java \
  Geometry.java \
  Material.java \
  Shader.java \
  GL14ShaderProgram.java \
  VertexShader.java \
  FragmentShader.java \
  GL14Shader.java \
  ShaderArgumentValue.java \
  ShaderArguments.java \
  ShaderObject.java \
  ShaderProgram.java \
  GLSLangShader.java \
  PointAttributes.java \
  LineAttributes.java \
  PolygonAttributes.java \
  BlendAttributes.java \
  DepthAttributes.java \
  StencilAttributes.java \
  AlphaAttributes.java \
  Appearance.java \
  AppearanceOverride.java \
  Shape3D.java \
  Sound.java \
  BackgroundSound.java \
  PointSound.java \
  ConeSound.java \
  ObjectSet.java \
  Group.java  \
  TransformGroup.java \
  SharedNode.java \
  SharedGroup.java \
  SwitchGroup.java \
  VertexGeometry.java \
  IndexedVertexGeometry.java \
  TriangleArray.java \
  TriangleFanArray.java \
  TriangleStripArray.java \
  QuadArray.java \
  QuadStripArray.java \
  PointArray.java \
  LineArray.java \
  LineStripArray.java \
  IndexedTriangleArray.java \
  IndexedTriangleStripArray.java \
  IndexedTriangleFanArray.java \
  IndexedLineArray.java \
  IndexedLineStripArray.java \
  IndexedQuadArray.java \
  IndexedQuadStripArray.java \
  Light.java \
  AmbientLight.java \
  DirectionalLight.java \
  SpotLight.java \
  PointLight.java \
  ClipPlane.java \
  Fog.java \
  Background.java \
  ColorBackground.java \
  SphereBackground.java \
  BoxBackground.java \
  ShapeBackground.java \
  ImageBackground.java \
  StencilBufferState.java \
  DepthBufferState.java \
  ColorBufferState.java \
  AccumulationBufferState.java \
  GeneralBufferState.java \
  Node2D.java \
  Leaf2D.java \
  Raster.java \
  BitmapRaster.java \
  ByteRaster.java \
  ImageRaster.java \
  Pixmap.java \
  Group2D.java \
  SharedNode2D.java \
  SharedGroup2D.java \
  PixelTransform.java \
  Scene.java \
  Scene2D.java \
  SimpleScene.java \
  MPViewportRenderable.java \
  RenderPass.java \
  MultipassScene.java \
  SimpleViewportLayer.java \
  MultipassViewportLayer.java \
  Viewport.java \
  SimpleViewport.java \
  CompositeViewport.java \
  MultipassViewport.java \
  CompositeLayer.java \
  SimpleLayer.java \
  ViewportLayer2D.java \
  Viewport2D.java \
  CompositeLayer2D.java \
  SimpleLayer2D.java \
  OffscreenTexture2D.java \
  MRTTexture2D.java \
  MRTOffscreenTexture2D.java \
  Texture1D.java \
  Texture2D.java \
  Texture3D.java \
  TextureCubicEnvironmentMap.java \
  MultipassTextureComponent.java \
  SceneGraphPath.java \
  ApplicationUpdateObserver.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-util_1.1.0.jar vecmath.jar

include ${PROJECT_ROOT}/make/Makefile.jav
