#*********************************************************************
#
#  (C) 2003 Yumetech, Inc
#    http://www.j3d.org/
#
# Package makefile for the org.j3d.aviatrix3d directory
#
# Author: Justin Couch
# Version: $Revision: 1.5 $
#
#*********************************************************************

PACKAGE = org.j3d.aviatrix3d

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = NodeUpdateListener.java \
  NodeUpdateHandler.java \
  SceneGraphObject.java \
  BoundingVolume.java \
  BoundingSphere.java \
  BoundingBox.java \
  BoundsUtils.java \
  Node.java \
  NodeComponent.java \
  Leaf.java \
  ImageComponent.java \
  ImageComponent2D.java \
  ImageComponent3D.java \
  Viewpoint.java \
  Geometry.java \
  Material.java \
  Texture.java \
  Texture2D.java \
  TextureAttributes.java \
  TexCoordGeneration.java \
  TextureUnit.java \
  Appearance.java \
  Shape3D.java \
  Group.java  \
  TransformGroup.java \
  View.java \
  VertexGeometry.java \
  TriangleArray.java \
  Light.java \
  DirectionalLight.java \
  SpotLight.java \
  PointLight.java \
  Fog.java \
  Background.java \
  ColorBackground.java \
  CullStage.java \
  DrawStage.java \
  SceneGraphPath.java \
  ViewEnvironment.java \
  DrawableSurface.java \
  RenderPipeline.java \
  RenderPipelineManager.java \
  SwitchGroup.java \

#  DefaultRenderManager.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-util.jar

include ${PROJECT_ROOT}/make/Makefile.jav
